version: '3'

#docker compose  --env-file ../../.env up -d
services:
  postgres:
    image: postgres:14.3
    container_name: postgres-db-curso-nestjs
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data