# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - "27018:27018"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_DATABASE: nest-pokemon
    volumes:
      - ../../mongo:/data/db
